<?php
return array(
    'Lysine\Application' => './base/application.php',
    'Lysine\Cache\Memcached' => './cache/memcached.php',
    'Lysine\Config' => './core.php',
    'Lysine\Db' => './db/db.php',
    'Lysine\Db\ActiveRecord' => './db/ar.php',
    'Lysine\Db\Adapter\Pdo' => './db/adapter/pdo/adapter.php',
    'Lysine\Db\Adapter\Pdo\Pgsql' => './db/adapter/pdo/pgsql.php',
    'Lysine\Db\Expr' => './db/expr.php',
    'Lysine\Db\IAdapter' => './db/db.php',
    'Lysine\Db\IStatement' => './db/db.php',
    'Lysine\Db\Pool' => './db/pool.php',
    'Lysine\Db\Select' => './db/select.php',
    'Lysine\Db\Statement\Pdo' => './db/statement/pdo.php',
    'Lysine\ICache' => './base/interfaces.php',
    'Lysine\Request' => './base/request.php',
    'Lysine\Request_Exception' => './base/request.php',
    'Lysine\Response' => './base/response.php',
    'Lysine\Response_Redirect' => './base/response.php',
    'Lysine\Router' => './base/router.php',
    'Lysine\Router_Abstract' => './base/router.php',
    'Lysine\Utils\Coll' => './utils/collection.php',
    'Lysine\Utils\Events' => './utils/events.php',
    'Lysine\Utils\Injection' => './utils/injection.php',
    'Lysine\View' => './base/view.php',
);